#!/bin/bash
set -e

help () {
  echo "consul-backup"
  echo "Backups or restore consul to s3"
  echo
  echo "Usage: consul-backup backup -h http://127.0.0.1:8500 -b somebucketname -f prefix"
  echo
  echo "backup | restore - Operation mode" 
  echo "-h | --host     - The Consul Host Address"
  echo "-b | --s3bucket  - The s3 bucket path to use, no trailing slash"
  echo "-f | --filename  - The prefix for the filename."
}

if [[ $# -ne 7 ]] ; then
    echo 'ERROR: All 4 arguments must be specified'
    help
    exit 1
fi


while [[ $# > 1 ]]
do
key="$1"

case $key in
    backup)
    OPERATION_MODE='backup'
    shift
    ;;
    restore)
    OPERATION_MODE='restore'
    shift
    ;;
    -h|--host)
    API_HOST="$2"
    shift
    ;;
    -b|--s3bucket)
    S3_URL="$2"
    shift
    ;;
    -f|--filename)
    FILENAME="$2"-$(date +%F_%R).snap
    shift
    ;;
    *)
    ;;
esac
shift
done

echo APIHOST = "{$API_HOST}"
echo S3_URL = "{$S3_URL}"
echo FILENAME = "{$FILENAME}"

doBackup() {
  echo "Performing a backup"
  #create snapshot
  consul snapshot save "$FILENAME"

  #Upload to s3
  aws s3 cp "$FILENAME" "$S3_URL/$FILENAME"

  #Remove file
  rm "$FILENAME"
}

doRestore() {
  echo "Performing a restoration"
}

case $OPERATION_MODE in
  backup)
  doBackup
  ;;
  restore)
  doRestore
  ;;
  *)
  echo "ERROR: say backup or restore in arguments"
  exit 1
  ;;
esac

