#!/bin/bash
set -e

help () {
  echo "consul-backup"
  echo "Backups or restore consul to s3"
  echo
  echo "Usage: consul-backup -m backup -h http://127.0.0.1:8500 -b s3://somebucket/backups/ -p prefix"
  echo "Usage: consul-backup -m restore -h http://127.0.0.1:8500 -b s3://somebucket/backups/ -f prefix-"
  echo
  echo "-m backup | restore - Operation mode" 
  echo "-h | --host     - The Consul Host Address"
  echo "-b | --s3bucket  - The s3 bucket path to use, no trailing slash"
  echo "-p | --prefix  - The prefix for the filename. Dont use with -f"
  echo "-f | --filename - The full filename to restore. Dont use with -p"
}

if [[ $# -ne 8 ]] ; then
    echo 'ERROR: All 4 arguments must be specified'
    echo 'For filename you must use or -p for backup prefix or -f for full name in restore'
    help
    exit 1
fi


while [[ $# > 1 ]]
do
  key="$1"
  case $key in
      -m|--mode)
      OPERATION_MODE="$2"
      shift
      ;;
      -h|--host)
      API_HOST="$2"
      shift
      ;;
      -b|--s3bucket)
      S3_URL="$2"
      shift
      ;;
      -p|--prefix)
      FILENAME="$2"-$(date +%F_%R).snap
      shift
      ;;
      -f|--filename)
      FILENAME="$2"
      shift
      ;;
      *)
      ;;
  esac
shift
done

echo OPERATION_MODE = "{$OPERATION_MODE}"
echo APIHOST = "{$API_HOST}"
echo S3_URL = "{$S3_URL}"
echo FILENAME = "{$FILENAME}"

doBackup() {
  echo
  echo "Performing a backup"
  #create snapshot
  consul snapshot save -http-addr=$API_HOST "$FILENAME"
  echo "File $FILENAME created. Uploading..."
  #Upload to s3
  echo "Uploading $FILENAME to $S3_URL/$FILENAME"
  aws s3 cp "$FILENAME" "$S3_URL/$FILENAME"
  echo "File $FILENAME uploaded. Removing.."
  #Remove file
  rm "$FILENAME"
  echo "Backup sucessfull"
}

doRestore() {
  echo "Performing a restoration"
  echo "Downloading $S3_URL/$FILENAME"

  aws s3 cp "$S3_URL/$FILENAME" "$FILENAME"
  consul snapshot restore -http-addr=$API_HOST "$FILENAME" 

  echo "Snapshot completed. Removing $FILENAME ..."
  #Remove file
  rm "$FILENAME"
  echo "Restore sucessfull"
}

case $OPERATION_MODE in
  backup)
  doBackup
  ;;
  restore)
  doRestore
  ;;
  *)
  echo "ERROR: pass operation mode (-m). Valid arguments: backup | restore"
  exit 1
  ;;
esac

